### ISSUE TITLE
start- error

### ISSUE THREAD

**Issue by Alexey-T** [medvosa/cuda_html_live_preview#10]
```
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_html_live_preview/__init__.py", line 13, in <module>
    process=Popen('python3 server.py')
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python3 server.py': 'python3 server.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.config/cudatext/py/cuda_html_live_preview/__init__.py", line 15, in <module>
    process=Popen('python server.py')
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python server.py': 'python server.py'
```

**Comment by ahreenah** [comment]
linux?
